### ISSUE TITLE
Create Permissions Auth

### ISSUE THREAD

**Issue by ThomasBouasli** [tbouasli/white-label-server#26]
### Tasks

- [x] Entities
    - [x]  Permission
    - [x]  Permission Group
    - [x] User
- [ ] Seeds 
    - [ ] Common
    - [ ] Admin
- [ ] Functions
    - [ ] Get all Permission Groups
    - [ ] Get Permission Group
    - [ ] Create Permission Group
    - [ ] Update Permission Group
        - [ ] Add Permission to Group
        - [ ] Remove Permission to Group
    - [ ] Delete Permission Group
    - [ ] Add Permission to Group to User
    - [ ] Remove Permission to Group from User
- [ ] Create Auth Guard based on JWT and Permissions
